#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceSerial)
Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceMock)
Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceOperation)
Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceCommand)
