#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategorySerialDevice)
Q_DECLARE_LOGGING_CATEGORY(logCategoryMockDevice)
Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceOperations)
