#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceSerial)
Q_DECLARE_LOGGING_CATEGORY(logCategoryDeviceMock)
Q_DECLARE_LOGGING_CATEGORY(logCategoryPlatformOperation)
Q_DECLARE_LOGGING_CATEGORY(logCategoryPlatformCommand)
