include(CheckCXXCompilerFlag)

if(UNIX)
    check_cxx_compiler_flag("-Wall" HAVE_WALL)
    if(HAVE_WALL)
        add_compile_options("-Wall")
    endif()

    check_cxx_compiler_flag("-Wextra" HAVE_WEXTRA)
    if(HAVE_WEXTRA)
        add_compile_options("-Wextra")
    endif()

    check_cxx_compiler_flag("-w" HAVE_W)
    if(HAVE_W)
        option(STRATA_COMP_W "Inhibit all warning messages" OFF)
        add_feature_info(STRATA_COMP_W STRATA_COMP_W "Inhibit all warning messages")
        if(STRATA_COMP_W)
            add_compile_options("-w")
        endif()
    endif()

    check_cxx_compiler_flag("-Werror" HAVE_WERROR)
    if(HAVE_WERROR)
        option(STRATA_COMP_WERROR "Make all warnings into errors" OFF)
        add_feature_info(STRATA_COMP_WERROR STRATA_COMP_WERROR "Make all warnings into errors")
        if(STRATA_COMP_WERROR)
            add_compile_options("-Werror")
        endif()
    endif()

    check_cxx_compiler_flag("-pipe" HAVE_PIPE)
    if(HAVE_PIPE)
        add_compile_options("-pipe")
    endif()

    check_cxx_compiler_flag("-Wno-c++98-compat" HAVE_CPP98_COMPAT)
    if(HAVE_CPP98_COMPAT)
        add_compile_options("-Wno-c++98-compat")
    endif()
endif()
