#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataServer)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataClient)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataDispatcher)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataClientsController)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataServerConnector)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataClientConnector)
Q_DECLARE_LOGGING_CATEGORY(logCategoryRequestsController)
