#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataServer)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataClient)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataDispatcher)
Q_DECLARE_LOGGING_CATEGORY(logCategoryStrataClientsController)
