import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/******************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-09-28 12:06:09.203 UTC-07:00
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias notifications: notifications
    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    QtObject {
        id: notifications
    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands

        // @command get_data
        property QtObject get_data: QtObject {
            signal commandSent()

            function update() {
                this.send()
            }

            function send() {
                platformInterface.send({
                    "cmd": "get_data"
                })
                commandSent()
            }
        }

        // @command set_data
        // @property value: int
        property QtObject set_data: QtObject {
            property int value: 0

            signal commandSent()

            function update(value) {
                this.set(value)
                this.send()
            }

            function set(value) {
                this.value = value
            }

            function send() {
                platformInterface.send({
                    "cmd": "set_data",
                    "payload": {
                        "value": value
                    }
                })
                commandSent()
            }
        }

        // @command set_values
        // @property value: int
        // @property value2: int
        // @property value3: int
        property QtObject set_values: QtObject {
            property int value: 0
            property int value2: 0
            property int value3: 0

            signal commandSent()

            function update(value, value2, value3) {
                this.set(value, value2, value3)
                this.send()
            }

            function set(value, value2, value3) {
                this.value = value
                this.value2 = value2
                this.value3 = value3
            }

            function send() {
                platformInterface.send({
                    "cmd": "set_values",
                    "payload": {
                        "value": value,
                        "value2": value2,
                        "value3": value3
                    }
                })
                commandSent()
            }
        }
    }
}
