import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12


/*******************************************************************************************
  * File auto-generated by PlatformInterfaceGenerator on 2021-02-22 16:22:23.679 UTC-08:00

  To create/update PlatformInterface.qml use PlatformInterfaceGenerator Tool.
  Refer: https://confluence.onsemi.com/display/BSK/Generating+a+PlatformInterface.qml+File
**********************************************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias notifications: notifications
    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    QtObject {
        id: notifications
    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands
    }
}
