import QtQuick 2.0

Item {
    function position_1(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led31_color = "green"

        platformInterface.demo_led12_color = "off"
        platformInterface.demo_led13_color = "off"
        platformInterface.demo_led14_color = "off"
        platformInterface.demo_led15_color = "off"
        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led22_color = "off"
        platformInterface.demo_led23_color = "off"
        platformInterface.demo_led24_color = "off"
        platformInterface.demo_led25_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led32_color = "off"
        platformInterface.demo_led33_color = "off"
        platformInterface.demo_led34_color = "off"
        platformInterface.demo_led35_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }
    function position_2(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"

        platformInterface.demo_led13_color = "off"
        platformInterface.demo_led14_color = "off"
        platformInterface.demo_led15_color = "off"
        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led23_color = "off"
        platformInterface.demo_led24_color = "off"
        platformInterface.demo_led25_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led33_color = "off"
        platformInterface.demo_led34_color = "off"
        platformInterface.demo_led35_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_3(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"

        platformInterface.demo_led14_color = "off"
        platformInterface.demo_led15_color = "off"
        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led24_color = "off"
        platformInterface.demo_led25_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led34_color = "off"
        platformInterface.demo_led35_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_4(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"

        platformInterface.demo_led15_color = "off"
        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led25_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led35_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_5(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"

        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_6(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"

        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_7(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"

        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_8(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"

        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_9(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led19_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led29_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"
        platformInterface.demo_led39_color = "green"

        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_10(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led19_color = "green"
        platformInterface.demo_led1A_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led29_color = "green"
        platformInterface.demo_led2A_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"
        platformInterface.demo_led39_color = "green"
        platformInterface.demo_led3A_color = "green"

        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_11(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led19_color = "green"
        platformInterface.demo_led1A_color = "green"
        platformInterface.demo_led1B_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led29_color = "green"
        platformInterface.demo_led2A_color = "green"
        platformInterface.demo_led2B_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"
        platformInterface.demo_led39_color = "green"
        platformInterface.demo_led3A_color = "green"
        platformInterface.demo_led3B_color = "green"

        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function position_12(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led19_color = "green"
        platformInterface.demo_led1A_color = "green"
        platformInterface.demo_led1B_color = "green"
        platformInterface.demo_led1C_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led29_color = "green"
        platformInterface.demo_led2A_color = "green"
        platformInterface.demo_led2B_color = "green"
        platformInterface.demo_led2C_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"
        platformInterface.demo_led39_color = "green"
        platformInterface.demo_led3A_color = "green"
        platformInterface.demo_led3B_color = "green"
        platformInterface.demo_led3C_color = "green"
    }
}
