import QtQuick 2.0

Item {

    function state1(){
        platformInterface.demo_led11_color = "off"
        platformInterface.demo_led12_color = "off"
        platformInterface.demo_led13_color = "off"
        platformInterface.demo_led14_color = "off"
        platformInterface.demo_led15_color = "off"
        platformInterface.demo_led16_color = "off"
        platformInterface.demo_led17_color = "off"
        platformInterface.demo_led18_color = "off"
        platformInterface.demo_led19_color = "off"
        platformInterface.demo_led1A_color = "off"
        platformInterface.demo_led1B_color = "off"
        platformInterface.demo_led1C_color = "off"
        platformInterface.demo_led21_color = "off"
        platformInterface.demo_led22_color = "off"
        platformInterface.demo_led23_color = "off"
        platformInterface.demo_led24_color = "off"
        platformInterface.demo_led25_color = "off"
        platformInterface.demo_led26_color = "off"
        platformInterface.demo_led27_color = "off"
        platformInterface.demo_led28_color = "off"
        platformInterface.demo_led29_color = "off"
        platformInterface.demo_led2A_color = "off"
        platformInterface.demo_led2B_color = "off"
        platformInterface.demo_led2C_color = "off"
        platformInterface.demo_led31_color = "off"
        platformInterface.demo_led32_color = "off"
        platformInterface.demo_led33_color = "off"
        platformInterface.demo_led34_color = "off"
        platformInterface.demo_led35_color = "off"
        platformInterface.demo_led36_color = "off"
        platformInterface.demo_led37_color = "off"
        platformInterface.demo_led38_color = "off"
        platformInterface.demo_led39_color = "off"
        platformInterface.demo_led3A_color = "off"
        platformInterface.demo_led3B_color = "off"
        platformInterface.demo_led3C_color = "off"
    }

    function state2(){
        platformInterface.demo_led11_color = "yellow"
        platformInterface.demo_led12_color = "yellow"
        platformInterface.demo_led13_color = "yellow"
        platformInterface.demo_led14_color = "yellow"
        platformInterface.demo_led15_color = "yellow"
        platformInterface.demo_led16_color = "yellow"
        platformInterface.demo_led17_color = "yellow"
        platformInterface.demo_led18_color = "yellow"
        platformInterface.demo_led19_color = "yellow"
        platformInterface.demo_led1A_color = "yellow"
        platformInterface.demo_led1B_color = "yellow"
        platformInterface.demo_led1C_color = "yellow"
        platformInterface.demo_led21_color = "yellow"
        platformInterface.demo_led22_color = "yellow"
        platformInterface.demo_led23_color = "yellow"
        platformInterface.demo_led24_color = "yellow"
        platformInterface.demo_led25_color = "yellow"
        platformInterface.demo_led26_color = "yellow"
        platformInterface.demo_led27_color = "yellow"
        platformInterface.demo_led28_color = "yellow"
        platformInterface.demo_led29_color = "yellow"
        platformInterface.demo_led2A_color = "yellow"
        platformInterface.demo_led2B_color = "yellow"
        platformInterface.demo_led2C_color = "yellow"
        platformInterface.demo_led31_color = "yellow"
        platformInterface.demo_led32_color = "yellow"
        platformInterface.demo_led33_color = "yellow"
        platformInterface.demo_led34_color = "yellow"
        platformInterface.demo_led35_color = "yellow"
        platformInterface.demo_led36_color = "yellow"
        platformInterface.demo_led37_color = "yellow"
        platformInterface.demo_led38_color = "yellow"
        platformInterface.demo_led39_color = "yellow"
        platformInterface.demo_led3A_color = "yellow"
        platformInterface.demo_led3B_color = "yellow"
        platformInterface.demo_led3C_color = "yellow"
    }

    function state3(){
        platformInterface.demo_led11_color = "green"
        platformInterface.demo_led12_color = "green"
        platformInterface.demo_led13_color = "green"
        platformInterface.demo_led14_color = "green"
        platformInterface.demo_led15_color = "green"
        platformInterface.demo_led16_color = "green"
        platformInterface.demo_led17_color = "green"
        platformInterface.demo_led18_color = "green"
        platformInterface.demo_led19_color = "green"
        platformInterface.demo_led1A_color = "green"
        platformInterface.demo_led1B_color = "green"
        platformInterface.demo_led1C_color = "green"
        platformInterface.demo_led21_color = "green"
        platformInterface.demo_led22_color = "green"
        platformInterface.demo_led23_color = "green"
        platformInterface.demo_led24_color = "green"
        platformInterface.demo_led25_color = "green"
        platformInterface.demo_led26_color = "green"
        platformInterface.demo_led27_color = "green"
        platformInterface.demo_led28_color = "green"
        platformInterface.demo_led29_color = "green"
        platformInterface.demo_led2A_color = "green"
        platformInterface.demo_led2B_color = "green"
        platformInterface.demo_led2C_color = "green"
        platformInterface.demo_led31_color = "green"
        platformInterface.demo_led32_color = "green"
        platformInterface.demo_led33_color = "green"
        platformInterface.demo_led34_color = "green"
        platformInterface.demo_led35_color = "green"
        platformInterface.demo_led36_color = "green"
        platformInterface.demo_led37_color = "green"
        platformInterface.demo_led38_color = "green"
        platformInterface.demo_led39_color = "green"
        platformInterface.demo_led3A_color = "green"
        platformInterface.demo_led3B_color = "green"
        platformInterface.demo_led3C_color = "green"
    }
}
