SET(CMAKE_SYSTEM_NAME           "Windows")
SET(CMAKE_SYSTEM_VERSION        "")
SET(CMAKE_SYSTEM_PROCESSOR      "x86-64")
SET(CMAKE_C_COMPILER            "x86_64-w64-mingw32-gcc-5.3-posix")
#SET(CMAKE_C_COMPILER            "x86_64-w64-mingw32-gcc-5.3-win32")
SET(CMAKE_CXX_COMPILER          "x86_64-w64-mingw32-g++-posix")
#SET(CMAKE_CXX_COMPILER          "x86_64-w64-mingw32-g++")


# Currently not using these
#SET(CMAKE_FIND_ROOT_PATH "/usr/include")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
