import QtQuick 2.12
import QtQuick.Controls 2.12
import tech.strata.common 1.0
import QtQml 2.12

/******************************************************************
  * This file must be replaced with one generated by PlatformInterfaceGenerator
  * if you want to use this template with a platform/board
******************************************************************/

PlatformInterfaceBase {
    id: platformInterface
    apiVersion: 2

    property alias notifications: notifications
    property alias commands: commands

    /******************************************************************
      * NOTIFICATIONS
    ******************************************************************/

    QtObject {
        id: notifications
    }

    /******************************************************************
      * COMMANDS
    ******************************************************************/

    QtObject {
        id: commands
    }
}
