#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryHcs)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsSignals)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsStorage)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsStorageCache)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsPlatformDocument)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsPlatform)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsNode)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsFwUpdater)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsDb)
Q_DECLARE_LOGGING_CATEGORY(logCategoryHcsClients)
