#pragma once

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCategoryUtils)
Q_DECLARE_LOGGING_CATEGORY(logCategoryQWTPlot)
Q_DECLARE_LOGGING_CATEGORY(logCategoryJLink)
Q_DECLARE_LOGGING_CATEGORY(logCategoryUserSettings)
Q_DECLARE_LOGGING_CATEGORY(logCategoryVersionUtils)
